# Generated by Django 3.2.4 on 2021-09-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('etitle', models.CharField(max_length=400)),
                ('epurpose', models.TextField(max_length=2000)),
                ('epic', models.ImageField(default='', upload_to='static/events')),
                ('edate', models.DateField()),
                ('sthanks', models.CharField(max_length=200)),
            ],
        ),
    ]
