# Generated by Django 3.2.4 on 2021-10-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_city_donate_membership_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtitle', models.CharField(max_length=200)),
                ('vdes', models.TextField(max_length=600)),
                ('thumb', models.ImageField(default='', upload_to='static/thumbnail/')),
                ('vlink', models.CharField(max_length=500)),
                ('vdate', models.DateField()),
            ],
        ),
    ]
